In [60]:
# importing the libraries
import numpy as np
import pandas as pd

In [61]:
# loading the dataset
dataset = pd.read_csv('/content/customer.csv')

In [62]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        50 non-null     int64 
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB


In [63]:
dataset.sample(15)

age  gender   review education purchased
19   97    Male     Poor        PG       Yes
5    31  Female  Average    School       Yes
23   96  Female     Good    School        No
9    74    Male     Good        UG       Yes
34   86    Male  Average    School        No
1    68  Female     Poor        UG        No
41   23    Male     Good        PG       Yes
47   38  Female     Good        PG       Yes
14   15    Male     Poor        PG       Yes
35   74    Male     Poor    School       Yes
17   22  Female     Poor        UG       Yes
32   92    Male  Average        UG       Yes
4    16  Female  Average        UG        No
11   74    Male     Good        UG       Yes
49   25  Female     Good        UG        No

In [64]:
# keeping only the ordianl features
dataset = dataset.iloc[ : , 2: ]

In [65]:
dataset.sample(5)

review education purchased
10   Good        UG       Yes
2    Good        PG        No
7    Poor    School       Yes
33   Good        PG       Yes
18   Good    School        No

In [66]:
dataset['review'].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [67]:
dataset['education'].value_counts()

education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [68]:
X = dataset.iloc[:,0:-1]
y = dataset.iloc[:,-1]

In [69]:
X.shape

(50, 2)

In [70]:
y.shape

(50,)

In [71]:
# importing train_test_split
from sklearn.model_selection import train_test_split

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state = 42)

In [73]:
X_train.shape

(40, 2)

In [74]:
# importing ordinal encoder
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(
    categories=[
        ['Poor', 'Average', 'Good'],
        ['School','UG','PG']
    ],
    dtype='int32'
)

In [75]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']],
               dtype='int32')

In [76]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [77]:
X_train = oe.transform(X_train)

In [78]:
X_train

array([[0, 0],
       [1, 1],
       [1, 2],
       [1, 1],
       [2, 2],
       [2, 0],
       [2, 2],
       [0, 2],
       [2, 2],
       [0, 1],
       [2, 1],
       [0, 1],
       [1, 2],
       [1, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 2],
       [2, 2],
       [1, 0],
       [1, 1],
       [2, 1],
       [2, 1],
       [0, 1],
       [1, 2],
       [2, 2],
       [0, 2],
       [0, 0],
       [2, 0],
       [2, 0],
       [2, 1],
       [0, 2],
       [2, 0],
       [2, 1],
       [1, 0],
       [0, 0],
       [2, 2],
       [0, 2],
       [0, 0],
       [2, 0]], dtype=int32)

In [79]:
X_test = oe.transform(X_test)

In [80]:
X_test

array([[1, 0],
       [0, 2],
       [1, 1],
       [0, 2],
       [0, 1],
       [2, 1],
       [0, 2],
       [2, 0],
       [1, 1],
       [0, 2]], dtype=int32)

In [81]:
from sklearn.preprocessing import LabelEncoder

In [82]:
le = LabelEncoder()

In [83]:
le.fit(y_train)

LabelEncoder()

In [84]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [85]:
y_test

13     No
39     No
30     No
45    Yes
17    Yes
48    Yes
26     No
25     No
32    Yes
19    Yes
Name: purchased, dtype: object

In [86]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [87]:
y_test

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1])

In [88]:
decoded = le.inverse_transform(y_test)
print("Decoded values:", decoded)

Decoded values: ['No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes']
